--DROP TABLE ORDERREPOSITORY;

CREATE TABLE ORDERREPOSITORY 
(
  ORDERREPID NUMBER(10) NOT NULL 
, STATUSPROCESSAMENTO INTEGER NOT NULL
, DATE_PROCESSAMENTO DATE
, DESCRIPTIONERROR VARCHAR2 (100)
, XMLDATA CLOB NOT NULL 
, CONSTRAINT ORDERREPOSITORY_PK PRIMARY KEY 
  (
    ORDERREPID 
  )
  ENABLE 
);

--DROP TABLE ORDERS;

CREATE TABLE ORDERS 
(
  ORDERID NUMBER(18,2) NOT NULL 
, CUSTOMERNAME VARCHAR2(50) NOT NULL 
, ORDERDATE DATE NOT NULL 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ORDERID
  )
  ENABLE 
);

--DROP TABLE ORDERITEMS;

CREATE TABLE ORDERITEMS 
(
  ORDERITEMID NUMBER(10) NOT NULL
, ORDERID NUMBER(10) NOT NULL
, PRODUCTNAME VARCHAR2(50) NOT NULL
, QUANTITY NUMBER NOT NULL
, PRICE VARCHAR2(50) NOT NULL
, CONSTRAINT ORDERITEMS_PK PRIMARY KEY
  (
    ORDERITEMID 
  )
  ENABLE 
);

ALTER TABLE ORDERITEMS
ADD CONSTRAINT ORDER_FK FOREIGN KEY
(
  ORDERID 
)
REFERENCES ORDERS
(
  ORDERID 
)ENABLE;
